export const Language = {
  en: {
    Profile: "Profile",
    Books: "Books",
    Create: "Create",
    "Login to your account.": "Login to your account.",
    Login: "Login",
    "Register Instead": "Register Instead",
    "Register a New account.": "Register a New account.",
    Register: "Register",
    "Login Instead": "Login Instead",
    "Your reading List": "Your reading List",
    "Add a New Book": "Add a New Book",
    "Saving...": "Saving...",
    "Time to start reading some books...":
      "Time to start reading some books...",
    logout: "logout",
    Contact: "Contact",
    About: "About",
    "Cool Stuff": "Cool Stuff",
    "The Number 1": "The Number 1",
    "Reading List App": "Reading List App",
    English: "English",
    German: "German",
    "Create Book": "Create Book",
    "Book Title": "Book Title",
    "Book Author": "Book Author",
    "Book Description": "Book Description",
  },
  de: {
    Profile: "Profil",
    Books: "Bücher",
    Create: "Erstellen",
    "Login to your account.": "Logge dich in dein Account ein.",
    Login: "Einloggen",
    "Register Instead": "Statdessen ein neues Konto registrieren.",
    "Register a New account.": "Registriere ein neues Konto.",
    Register: "Registrieren",
    "Login Instead": "Statdessen einloggen",
    "Your reading List": "Deine Lese Liste",
    "Add a New Book": "Neues Buch hinzufügen",
    "Saving...": "Speichern...",
    "Time to start reading some books...": "Zeit ein paar Bücher zu lesen...",
    logout: "ausloggen",
    Contact: "Kontakte",
    About: "Über",
    "Cool Stuff": "Cooles Zeug",
    "The Number 1": "The Nummer 1",
    "Reading List App": "Bücherlisten App",
    English: "Englisch",
    German: "Deutsch",
    "Create Book": "Buch Erstellen",
    "Book Title": "Buch Titel",
    "Book Author": "Buch Author",
    "Book Description": "Buch Beschreibung",
  },
};
