export const Language = {
  en: {
    Profile: "Profile",
    Books: "Books",
    Create: "Create",
    "Login to your account.": "Login to your account.",
    Login: "Login",
    "Register Instead": "Register Instead",
    "Register a New account.": "Register a New account.",
    Register: "Register",
    "Login Instead": "Login Instead",
    "Your reading List": "Your reading List",
    "Add a New Book": "Add a New Book",
    "Saving...": "Saving...",
    "Time to start reading some books...":
      "Time to start reading some books...",
    logout: "logout",
    Contact: "Contact",
    About: "About",
    "Cool Stuff": "Cool Stuff",
    "The Number 1": "The Number 1",
    "Reading List App": "Reading List App",
    English: "English",
    German: "German",
    "Create Book": "Create Book",
    "Book Title": "Book Title",
    "Book Author": "Book Author",
    "Book Description": "Book Description",
  },
  de: {
    Profile: "Profil",
    Books: "Bücher",
    Create: "Erstellen",
    "Login to your account.": "Logge dich in dein Account ein.",
    Login: "Einloggen",
    "Register Instead": "Statdessen ein neues Konto registrieren.",
    "Register a New account.": "Registriere ein neues Konto.",
    Register: "Registrieren",
    "Login Instead": "Statdessen einloggen",
    "Your reading List": "Deine Lese Liste",
    "Add a New Book": "Neues Buch hinzufügen",
    "Saving...": "Speichern...",
    "Time to start reading some books...": "Zeit ein paar Bücher zu lesen...",
    logout: "ausloggen",
    Contact: "Kontakte",
    About: "Über",
    "Cool Stuff": "Cooles Zeug",
    "The Number 1": "Die Nummer 1",
    "Reading List App": "Bücherlisten App",
    English: "Englisch",
    German: "Deutsch",
    "Create Book": "Buch Erstellen",
    "Book Title": "Buch Titel",
    "Book Author": "Buch Author",
    "Book Description": "Buch Beschreibung",
  },
  ja: {
    Profile: "プロフィール",
    Books: "本",
    Create: "作成",
    "Login to your account.": "アカウントにログインします。",
    Login: "ログイン",
    "Register Instead": "代わりに登録",
    "Register a New account.": "新しいアカウントを登録します。",
    Register: "登録",
    "Login Instead": "代わりにログイン",
    "Your reading List": "あなたの読書リスト",
    "Add a New Book": "新しい本を追加",
    "Saving...": "保存中...",
    "Time to start reading some books...": "本を読み始める時間です...",
    logout: "ログアウト",
    Contact: "連絡先",
    About: "約",
    "Cool Stuff": "クールなもの",
    "The Number 1": "ナンバーワン",
    "Reading List App": "読書リストアプリ",
    English: "英語",
    German: "ドイツ語",
    "Create Book": "本を作成",
    "Book Title": "本のタイトル",
    "Book Author": "本の著者",
    "Book Description": "本の説明",
  },
  fr: {
    Profile: "Profil",
    Books: "Livres",
    Create: "Créer",
    "Login to your account.": "Connectez-vous à votre compte.",
    Login: "Connexion",
    "Register Instead": "S'inscrire à la place",
    "Register a New account.": "Enregistrer un nouveau compte.",
    Register: "S'inscrire",
    "Login Instead": "Se connecter à la place",
    "Your reading List": "Votre liste de lecture",
    "Add a New Book": "Ajouter un nouveau livre",
    "Saving...": "Enregistrement...",
    "Time to start reading some books...":
      "Il est temps de commencer à lire des livres...",
    logout: "déconnexion",
    Contact: "Contact",
    About: "À propos",
    "Cool Stuff": "Choses cool",
    "The Number 1": "Le numéro 1",
    "Reading List App": "Application de liste de lecture",
    English: "Anglais",
    German: "Allemand",
    "Create Book": "Créer un livre",
    "Book Title": "Titre du livre",
    "Book Author": "Auteur du livre",
    "Book Description": "Description du livre",
  },
};
